[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.13"
src = "src"
test = "test"

[profile.ci]
fuzz_runs = 10_000
verbosity = 4

# See more config options https://github.com/gakonst/foundry/tree/master/config
