[default]
bytecode_hash = "none"
libs = ['lib']
optimizer_runs = 1000000
out = 'out'
solc = "0.8.13"
src = 'src'

#eth-rpc-url = ""

# See more config options https://github.com/gakonst/foundry/tree/master/config
