[default]
bytecode_hash = "none"
eth-rpc-url = "https://mainnet.infura.io"
libs = ['lib']
optimizer_runs = 1000000
out = 'out'
solc = "0.8.13"
src = 'src'

# See more config options https://github.com/gakonst/foundry/tree/master/config
